FROM osallou/my

RUN apt-get update && apt-get install -y curl ldap-utils openssh-client putty-tools
RUN curl -sL https://sentry.io/get-cli/ | bash
COPY gomngr.sh /opt/gomngr.sh
COPY crontask.sh /opt/crontask.sh
#COPY crontab /etc/cron.d/my-cron
#RUN chmod 0644 /etc/cron.d/my-cron
#RUN touch /var/log/cron.log

#ENTRYPOINT echo "export SENTRY_DSN=$SENTRY_DSN" > /root/.env && cron && tail -f /var/log/cron.log
ENTRYPOINT /opt/gomngr.sh
